name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: What happened? What did you expect?
    validations: { required: true }
  - type: input
    attributes: { label: Extension version }
  - type: input
    attributes: { label: Browser & OS }
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Step-by-step, minimal example if possible
  - type: textarea
    attributes:
      label: Additional context / screenshots
